### ISSUE TITLE
Concede leads to own team as next team

### ISSUE THREAD

**Issue by liquidblock** [querqueq/untitled#14]
To reproduce:
- Select some words as Red Spymaster, enter a tip and submit the tip
- Concede as Red Spy
- Now it is the turn of the Red Spymaster

Root cause:
https://github.com/querqueq/untitled/blob/2dcb23acbb4ef4659ca17057ca4ab260122ff5b1/codenames-service/src/Game/Logic.hs#L106
Need to be next team and not `activeTeam`

**Comment by querqueq** [comment]
Fixed
