### ISSUE TITLE
Loosing a game does not lead to the turn of the next team

### ISSUE THREAD

**Issue by liquidblock** [querqueq/untitled#15]
To reproduce:
- Select some words, and submit a tip as Red Spymaster
- Select an assassin word as Red Spy
- Now it is still the turn of the Red Team and the team can not concede because they already lost

Code:
https://github.com/querqueq/untitled/blob/2dcb23acbb4ef4659ca17057ca4ab260122ff5b1/codenames-service/src/Game/Logic.hs#L94
I think there needs to be an additional `TurnOf` effect of the next team.

**Comment by querqueq** [comment]
Ignore the #84b0775 commit, it was for another issue (#14)
I added an Inducer that always adds a `TurnOf` effect whenever a team loses.
