### ISSUE TITLE
Add number of cards for each team in GET request of a game

### ISSUE THREAD

**Issue by liquidblock** [querqueq/untitled#4]
For the request GET https://{server}/games/{game} please add the number of cards for each team.
E.g. `"cards": {"team-1": 8, "team-2": 7}` (to be defined)
The number of cards always reflects the overall number of cards (regardless of revealed=true nor false).
This information is needed by the client to display the Score.
Alternatively the score could be passed in the response, because the client can always calculate:
`score = allCards - revealedCards` or `allCards = score + revealedCards`

**Comment by querqueq** [comment]
Implemented with 3cc26f7

Added the following to response of GET /games/{gameId}

```json
"remainingWords": [["Red", 8], ["Blue", 7]]
```
