### ISSUE TITLE
Add current submitted tip in GET request of a game

### ISSUE THREAD

**Issue by liquidblock** [querqueq/untitled#5]
For the request GET https://{server}/games/{game} please add the currently submitted tip if the `currentRole` is `Spy`.
To display the current submitted tip, the client would need to find the last "TipSubmitted" effect in https://{server}/games/{game}/moves. In case of a reconnect (e.g. by refreshing the page, crash, etc.) the currently submitted tip could be added to `GET https://{server}/games/{game}`
E.g. `"currentTip": ["Hello", 4]` (when `"currentRole": "Spy"`) and `"currentTip": null` (when `"currentRole": "Spymaster"`)
In that case the last "TipSubmitted" effect would be `{"tag": "TipSubmitted", "contents": ["Hello", 4]}`

It would be nice if the client could render the current bord state (without history) only with the `https://{server}/games/{game}` resource.

**Comment by querqueq** [comment]
Why would only the Spy need the current submitted tip? Wouldn't Spymasters from other teams also like to see the tip?

**Comment by liquidblock** [comment]
The `currentRole` i am refering to is from the response of a request to GET https://{server}/games/{game}. See https://github.com/querqueq/untitled/blob/codenames-service/codenames-service/API.md#response-2.
When working with the response a also accidentally assumed that `currentRole` refers to the role of the player, but it represents the role of the player allowed to submit a move.
Maybe also rename `currentRole` and return something like `"currentTurn": { "team": 1, "role": "Spy", "tip": ["Hello", 2] }` where all information of the current turn is bundled. The `tip` should be `null` if it is the turn of the `Spymaster`.

**Comment by querqueq** [comment]
* Renamed `currentRole` to `activeRole`
* The active team is always the first team in `teamOrder`
* Added `latestTip` and `latestMove`

/games/0/moves
```json
[
  {
    "effects": [
      {
        "tag": "TipSubmitted",
        "contents": [
          "explosion",
          3
        ]
      }
    ],
    "no": 0,
    "move": {
      "tag": "Tip",
      "contents": [
        "explosion",
        3
      ]
    }
  },
  {
    "effects": [
      {
        "tag": "Selected",
        "contents": 5
      }
    ],
    "no": 1,
    "move": {
      "tag": "Select",
      "contents": 5
    }
  },
  {
    "effects": [
      {
        "tag": "Selected",
        "contents": 1
      }
    ],
    "no": 2,
    "move": {
      "tag": "Select",
      "contents": 1
    }
  }
]
```

/games/0
```json
{
  "latestMove": {
    "effects": [
      {
        "tag": "Selected",
        "contents": 1
      }
    ],
    "no": 2,
    "move": {
      "tag": "Select",
      "contents": 1
    }
  },
  "activeRole": "Spy",
  "teamOrder": [
    "Red",
    "Blue"
  ],
  "latestTip": {
    "effects": [
      {
        "tag": "TipSubmitted",
        "contents": [
          "explosion",
          3
        ]
      }
    ],
    "no": 0,
    "move": {
      "tag": "Tip",
      "contents": [
        "explosion",
        3
      ]
    }
  },
  "words": [...]
}
```

**Comment by querqueq** [comment]
I'll also add the current scores. Would then anything else be missing?

**Comment by liquidblock** [comment]
Concerning the GET `https://{server}/games/{game}` only #4 (current scores) are missing.
But fetching a game with GET `https://{server}/games/{game}` and then using GET `https://{server}/games/{game}/moves` only for updates is not sufficient to update the game-state, because the owner of a card is not revealed in that resource, therefore i can not use GET `https://{server}/games/{game}` for #9, but i would need to only use the GET `https://{server}/games/{game}` resource.
